Adapting the project to the frontend crud carton
Ludogorie-Soft/lukeria-erp-api pull request #11
Opened 2023-07-13 10:12 UTC by berki0

I release this branch for verification, here I have changed the code so that it can be used by the FrontEnd

2023-07-14 06:02 UTC, idimitrovRz requested changes

2023-07-14 06:02 UTC, idimitrovRz commented on src/main/java/com/example/ludogoriesoft/lukeriaerpapi/dtos/CartonDTO.java
> -    @Min(value = 1, message = "Цената трябва да бъде по-голяма от 0!")
Why this is deleted?
Why the type is change from Double to double?

2023-07-14 06:02 UTC, idimitrovRz commented on src/main/java/com/example/ludogoriesoft/lukeriaerpapi/dtos/CartonDTO.java
> +    private Double price;
I think that it's a bad practice do use Double for price.
Please, check these articles: 
1. https://medium.com/@cancerian0684/which-data-type-would-you-choose-for-storing-currency-values-like-trading-price-dd7489e7a439
2. https://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency

2023-07-18 09:52 UTC, BelisAliosmanova approved these changes
Everything looks very well done. I approve the changes made

2023-07-18 09:54 UTC, merged