Upload package images
Ludogorie-Soft/lukeria-erp-api pull request #20
Opened 2023-08-29 07:54 UTC by BelisAliosmanova

Upload package images 
- make a functionality to edit, delete and show  them

2023-08-31 19:20 UTC, berki0 reviewed
Everything looks fine, the task is successful

2023-08-31 19:21 UTC, berki0 approved these changes

2023-09-01 05:22 UTC, berki0 approved these changes

2023-09-01 05:33 UTC, idimitrovRz requested changes
I have just some tiny notes. Great work!

2023-09-01 05:33 UTC, idimitrovRz commented on src/main/java/com/example/ludogoriesoft/lukeriaerpapi/services/InvoiceService.java
> +           return 2000000000L;
Do not use magic numbers:
https://stackoverflow.com/questions/47882/what-is-a-magic-number-and-why-is-it-bad

2023-09-01 05:33 UTC, idimitrovRz commented on src/main/java/com/example/ludogoriesoft/lukeriaerpapi/services/InvoiceService.java
> +        return Long.parseLong(maxLastDigitNumber);
If maxLastDigitNumber is null, an exception will be thrown because it can't be parsed

2023-09-01 05:33 UTC, idimitrovRz commented on src/main/java/com/example/ludogoriesoft/lukeriaerpapi/services/InvoiceService.java
> +        return Long.parseLong(maxLastDigitNumber);
maybe we can use something like "orElse("0")

2023-09-01 05:33 UTC, idimitrovRz commented on src/test/java/com/example/ludogoriesoft/lukeriaerpapi/services/ClientQueryServiceTest.java
> +        // Създаване на мокнати данни
It's better to write comment in English

2023-09-01 06:10 UTC, idimitrovRz commented on src/main/java/com/example/ludogoriesoft/lukeriaerpapi/services/InvoiceService.java
> +    public static final Long FIRS_INVOICE_NUMBER = 2000000000L;
FIRST

2023-09-01 06:10 UTC, idimitrovRz approved these changes

2023-09-01 06:24 UTC, merged